# Build pipeline for the two docker images

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: ls client/message-log
  displayName: 'Listing files'

- task: Docker@2
  displayName: 'Docker Login'
  inputs:
    containerRegistry: 'SebugDockerHub'
    command: 'login'

- task: Docker@2
  displayName: 'Building postgresql docker image'
  inputs:
    containerRegistry: 'SebugDockerHub'
    repository: 'sebug/postgresql-messagelog'
    command: 'build'
    Dockerfile: 'postgresql/Dockerfile'
    tags: '$(Build.BuildId)'

- task: Docker@2
  displayName: 'Pushing postgresql docker image'
  inputs:
    containerRegistry: 'SebugDockerHub'
    repository: 'sebug/postgresql-messagelog'
    command: 'push'
    tags: '$(Build.BuildId)'

- script: cp message-log/Dockerfile . && docker build -t sebug/messagelog-client:$(Build.BuildId) .
  workingDirectory: client/message-log

- task: Docker@2
  displayName: 'Pushing messagelog client'
  inputs:
    containerRegistry: 'SebugDockerHub'
    repository: 'sebug/messagelog-client'
    command: 'push'
    tags: '$(Build.BuildId)'

- task: CmdLine@2
  displayName: 'Writing docker-compose'
  inputs:
    script: |
      mkdir -p $BUILD_ARTIFACTSTAGINGDIRECTORY/drop
      cat docker-compose.yml | sed -E "s/messagelog-client:[[:digit:]]*/messagelog-client:$BUILD_BUILDID/" | sed -E "s/postgresql-messagelog:[[:digit:]]*/postgresql-messagelog:$BUILD_BUILDID/" > $BUILD_ARTIFACTSTAGINGDIRECTORY/drop/docker-compose.yml
      ls $BUILD_ARTIFACTSTAGINGDIRECTORY
      ls $BUILD_ARTIFACTSTAGINGDIRECTORY/drop
      echo "And that should be it"
 
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/drop'
    ArtifactName: 'drop'
    publishLocation: 'Container'