# Build pipeline for the two docker images

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: ls client/message-log
  displayName: 'Listing files'

- task: Docker@2
  displayName: 'Docker Login'
  inputs:
    containerRegistry: 'SebugDockerHub'
    command: 'login'

- task: Docker@2
  displayName: 'Building postgresql docker image'
  inputs:
    containerRegistry: 'SebugDockerHub'
    repository: 'sebug/postgresql-messagelog'
    command: 'build'
    Dockerfile: 'postgresql/Dockerfile'
    tags: '$(Build.BuildId)'

- task: Docker@2
  displayName: 'Pushing postgresql docker image'
  inputs:
    containerRegistry: 'SebugDockerHub'
    repository: 'sebug/postgresql-messagelog'
    command: 'push'
    tags: '$(Build.BuildId)'

- script: cd client/message-log/message-log && docker build -t sebug/messagelog-client:$(Build.BuildId) .

- task: Docker@2
  displayName: 'Pushing messagelog client'
  inputs:
    containerRegistry: 'SebugDockerHub'
    repository: 'sebug/messagelog-client'
    command: 'push'
    tags: '$(Build.BuildId)'
