version: '3'
services:
  messagelogclient:
    image: "sebug/messagelog-client:334"
    ports:
     - "9090:80"
    env_file:
     - ./messagelogclient.env
  logdb:
    image: "sebug/postgresql-messagelog:334"
    ports:
     - "5432:5432"
    env_file:
     - ./database.env
    volumes:
     - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local