do $$
BEGIN
IF NOT EXISTS (
   SELECT *
   FROM INFORMATION_SCHEMA.COLUMNS
   WHERE TABLE_NAME = 'Event'
   AND COLUMN_NAME = 'IsArchived') THEN

ALTER TABLE "Event" ADD COLUMN "IsArchived" BOOLEAN NOT NULL DEFAULT false;

END IF;
END;
$$;
